### ISSUE TITLE
Links show up to the right of the text when processing anchor tag

### ISSUE THREAD

**Issue by yangl6** [peterdemartini/html5-to-pdf#10]
When I try to generate pdf files, everything works like a charm except the anchor tag. The link, which is defined in the href property in the anchor tag, is visible and appended to the text of the anchor tag. This cause the entire layout to be pretty messy. 

For example, if I have a anchor tag in the html file: 

` <a class="post-link" href="http://example.org">Hello world!</a>`,
Generated pdf file would contain:
Hello world! (http://example.org)

Could you please help me out with this issue? Is there any way to hide the unwanted links enclosed with the round brackets. 

Thanks.

Best regards,
Leo

**Comment by peterdemartini** [comment]
@yangl6 html5-to-pdf uses a library called nightmare, which uses electron under the hood. I am not entirely sure if they provide an API to change this easily. I personally do not have the time to dig into this. However I welcome you to try and fix this, and submit a pull request.
