### ISSUE TITLE
Running on AWS Ubuntu 14.04 gets stuck when calling build

### ISSUE THREAD

**Issue by biri** [peterdemartini/html5-to-pdf#18]
I am trying to run html5-to-pfd on my AWS Ubuntu 14.04 and when build is getting called it just gets stuck. I investigated the issue and found that there is a problem with the electron module in the nightmare module. Please refer to 

https://github.com/segmentio/nightmare/issues/224

https://github.com/segmentio/nightmare/issues/534
http://stackoverflow.com/questions/34795037/nightmare-js-not-working-as-expected-on-ubuntu-linux-cloud-server

Apparently Electron requires an X display and  since the server doesn't have a display it's a problem. There is a suggested solution to use Xvfb to provide a virtual one. Need to install xvfb, and run xvfb-run.
Any chance to implement it in the release or can you please suggest a way to use it with current release ?

Thanks.

**Comment by peterdemartini** [comment]
I think using xvfb is the right way. I would do something like this:

```bash
apt-get update && \
    apt-get install -y \
        xvfb \
        x11-xkb-utils \
        xfonts-100dpi \
        xfonts-75dpi \
        xfonts-scalable \
        xfonts-cyrillic \
        x11-apps \
        clang \
        libdbus-1-dev \
        libgtk2.0-dev \
        libnotify-dev \
        libgnome-keyring-dev \
        libgconf2-dev \
        libasound2-dev \
        libcap-dev \
        libcups2-dev \
        libxtst-dev \
        libxss1 \
        libnss3-dev \
        gcc-multilib \
        g++-multilib \
        xauth \
        git \
        sudo \
        --no-install-recommends
xvfb-run --server-args="-screen 9 1024x768x24" html5-to-pdf ...
```

**Comment by biri** [comment]
I will try it, thanks

**Comment by XoneFobic** [comment]
So, we need to run this in a virtual-screen on production now?
