### ISSUE TITLE
Electron requirements not clear

### ISSUE THREAD

**Issue by gerhardcit** [peterdemartini/html5-to-pdf#23]
Is it possible that you can make the Electron requirements clear for running this on a Linux Server.
Are there desktop components requirements that has to be be in place?
Do you have to stall Electron with npm in the project you use this etc?
It would be very helpful. Thx.

I got this working great on a mac dev environment but the ` htmlToPDF.build(function (err, buf) {` just hangs on the Ubuntu server without any errors returned.

**Comment by soryy708** [comment]
We're having the same issue.
I tried installing Ubuntu on my machine (in a VM) and it all worked flawlessly - this definitely has something to do with the way the server is configured.

**Comment by gerhardcit** [comment]
@soryy708 , that is Ubuntu Server only, no desktop version?
How do you configure the display for Electron to run a headless browser?

**Comment by soryy708** [comment]
The one I tested on was a desktop version. Sorry for the confusion.

**Comment by gerhardcit** [comment]
@peterdemartini , could you help with the explanation of Electron on a non-Desktop OS?

**Comment by soryy708** [comment]
Looks like Electron needs an X server, which Ubuntu Server doesn't have. You can use Xvfb to create a "fake" X server. https://www.npmjs.com/package/xvfb
Though I didn't get it working yet.

**Comment by soryy708** [comment]
Here's a useful thing: https://github.com/segmentio/nightmare/issues/224

**Comment by soryy708** [comment]
Try this:

# Install dependencies
apt-get update &&\
    apt-get install -y libgtk2.0-0 libgconf-2-4 \
    libasound2 libxtst6 libxss1 libnss3 xvfb
npm install segmentio/nightmare

# Start Xvfb
Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
export DISPLAY=:9.0

# Test it
apt-get install vim
vim index.js
# <paste in example>
node index.js

**Comment by peterdemartini** [comment]
Thanks @soryy708. It would be great to add a couple examples in the readme and add an example `Dockerfile`. If you are interested in helping that would be awesome, but if not, I will try to get to it as soon as I can.

**Comment by soryy708** [comment]
I don't know how to work with docker but I'll add a paragraph in the readme.

**Comment by soryy708** [comment]
@gerhardcit Did this work?

**Comment by gerhardcit** [comment]
@soryy708, i tried something like that but gave up.
Then tried phantom again, ended up with 6.7Mb email for 7 page pdf.
Redid it using pdfmake (no headless browser) and ended up with 400kb pdf document.
So for document generation, headless browsers are in my view not a great way to go.
