### ISSUE TITLE
Images is rendered not fully

### ISSUE THREAD

**Issue by nkovalenko-sc** [peterdemartini/html5-to-pdf#25]
Hi. I'm trying to render 2 images: scale.png and arrow.png. In 50% of cases I see not full images:
![chartfull](https://cloud.githubusercontent.com/assets/25153097/25899051/03cd135c-3597-11e7-92eb-3629d5bb68b2.PNG)
![chartnone](https://cloud.githubusercontent.com/assets/25153097/25899049/03cc04c6-3597-11e7-984a-cde14c0414ad.PNG)
![chartoneimage](https://cloud.githubusercontent.com/assets/25153097/25899050/03cd1528-3597-11e7-8ad9-77cd7adf6f99.PNG)
![chartpart](https://cloud.githubusercontent.com/assets/25153097/25899052/03d263d4-3597-11e7-8ae0-91226f0f458a.PNG)
Size of each image is 5-6 kb.
How to solve it?

**Comment by peterdemartini** [comment]
You can set the `renderDelay` to something higher and that should give more time to show up.

**Comment by nkovalenko-sc** [comment]
Thank you a lot!
