### ISSUE TITLE
The example code is missing some brackets etc. 

### ISSUE THREAD

**Issue by dwjohnston** [peterdemartini/html5-to-pdf#29]
Unless this is some ES7 feature I'm not aware of, the example code will not run. 

It currently reads: 

```
HTMLToPDF = require 'html5-to-pdf'
htmlToPDF = new HTMLToPDF {
  inputPath: './path/to/input.html'
}

htmlToPDF.build (error, buf) =>
  throw error if error?
  # buf is the PDF as buffer
  # Done!
```

**Comment by peterdemartini** [comment]
That is a coffee-script example.

**Comment by dwjohnston** [comment]
I figured it was something like that.  I figure this is what #15 is about too. Possibly update your doc to mention that it's coffeescript.
