### ISSUE TITLE
v2.2.8 is missing dist directory

### ISSUE THREAD

**Issue by alexanderwallin** [peterdemartini/html5-to-pdf#30]
I just installed `html5-to-pdf` and noticed `dist/` didn't get shipped. Resolved temporarily by installing and invoking `coffee-script/register` myself.

Cheers for a cool lib!

**Comment by peterdemartini** [comment]
Aw, the travis build failed to compile the dist folder. It is building 2.2.9 now and it should work.

**Comment by alexanderwallin** [comment]
Cool, thanks!
