### ISSUE TITLE
Javascript function to execute 

### ISSUE THREAD

**Issue by levi-blodgett** [peterdemartini/html5-to-pdf#31]
I looked at https://github.com/peterdemartini/html5-to-pdf/issues/13, but I wasn't quite sure how to actually implement this.

I'm new to JS, so this is a bit confusing for sure.

And I get an error on my html that require isn't even defined.

Once someone gets a moment, could they assist? @peterdemartini perhaps?

**Comment by soryy708** [comment]
I don't understand your question.

Are you trying to run this in NodeJS? Or you're trying to run in a browser?

**Comment by courtneyschwartz** [comment]
@levi-blodgett It sounds like you're also new to Node, right? Node isn't "regular" JavaScript that you run in a browser.
#13 was about including JavaScript in the page that's being converted from HTML to PDF. 
It sounds like you are trying to run this app (which isn't inside any HTML necessarily) in a browser. You won't get that error if you run it from the command line like `node myapp.js`
