### ISSUE TITLE
Library silently fails if running on headless server

### ISSUE THREAD

**Issue by soryy708** [peterdemartini/html5-to-pdf#33]
If html5-to-pdf is run on a headless server (like an Ubuntu server), it will silently fail.
Here's an idea for a feature:
Use [node Xvfb](https://www.npmjs.com/package/xvfb) to run Xvfb as needed.

**Comment by bshrram** [comment]
@peterdemartini is there any fix for this issue (before release 3 ) ?

**Comment by peterdemartini** [comment]
I am sorry, I don’t have any plans to fix this issue in the older version.
