### ISSUE TITLE
<a> elements are rendered with their link visually

### ISSUE THREAD

**Issue by actuallymentor** [peterdemartini/html5-to-pdf#35]
For some reason html like this:

```html
<a href='https://ama.zing'>Thing</a>
```

Is rendered in the pdf as the visual equivalent of:

```html
<a href='https://ama.zing'>Thing (https://ama.zing)</a>
```

I can't find anything in the documentation to indicate this is expected behaviour. How do I prevent this from happening?

**Comment by evanfrawley** [comment]
Appears that this bug has resurfaced in the latest version (4.0.1)

**Comment by HarryPeach** [comment]
Also getting this issue on 4.0.1

@peterdemartini Could this issue be re-opened?
