### ISSUE TITLE
Using htmlbootstrap template.

### ISSUE THREAD

**Issue by vasyldemchuk** [peterdemartini/html5-to-pdf#42]
Hey, 

I can not get working htmlbootstrap template. 
Example:

`const html5ToPDF = new html5pdf({
                inputBody: html,
                outputPath: filePath,
                template: 'htmlbootstrap'
            })`

It works fine when I use bootstrap.css via include.

Please advice!!

**Comment by peterdemartini** [comment]
This should be fixed v4.0.1
