### ISSUE TITLE
Security breach - secret key in .travis.yml

### ISSUE THREAD

**Issue by sonquer** [peterdemartini/html5-to-pdf#53]
https://github.com/peterdemartini/html5-to-pdf/blob/af6b4b760732ad34ba73ef1d7e14cfbdb6fa9d69/.travis.yml#L21

You can keep it in Travis Environment Variables 😉

**Comment by peterdemartini** [comment]
That is **NOT** a security breach, that value is encrypted and can only be used on this repo. Putting it in the environment settings only makes it easier to manage because you don't have to commit to change it.

Unless you have a another reason why this is a security breach, I am closing this.
