### ISSUE TITLE
no pdf generated

### ISSUE THREAD

**Issue by BenjaminHorn** [peterdemartini/html5-to-pdf#6]
Hi @peterdemartini !

Excellent repo, exactly what I need. Unfortunately even with some basic code no pdf generated.
I made a repository for demonstration: https://github.com/BenjaminHorn/html5-to-pdf-test.

```Javascript
var HTMLToPDF = require("html5-to-pdf");
var path = require("path");

var htmlToPDF = new HTMLToPDF({
  inputPath: path.resolve(__dirname, 'index.html'),
  inputBody: 'asdas',
  renderDelay: 200,
  outputPath: path.resolve(__dirname, 'output.pdf')
});

htmlToPDF.build(function(err){
  console.log('sdf');
  console.log('error: ' + err);
  if (err) throw err;
    
});

process.exit()
```

No error, or `console.log` output from `htmlToPDF.build`.
**node: 4.6.0**

Thanks

**Comment by peterdemartini** [comment]
Hello,

Thanks for making the example. It looks as if you are process exiting at the end of the script, this will kill all asynchronous processes before they finish. Meaning that the PDF will never build. I would add it in the build callback function instead.
