### ISSUE TITLE
No image rendered into PDF

### ISSUE THREAD

**Issue by TomFreudenberg** [peterdemartini/html5-to-pdf#7]
Hi Peter @peterdemartini 

thanks for sharing that stuff - looks really useful.

I am struggling a bit with images because those are not rendered into my PDF. I just use the command line tool 

```
./node_modules/html5-to-pdf/command.js --page-size A4 --landscape --margin-type 2 --include demo.css --output demo.pdf demo.html
```

I have two images:

```
  <div id="desy-logo">
     <img src="desy-logo.svg">
  </div>
  <div id="photo">
     <img src="photo.png">
  </div>
```

The HTML shows the images but not the PDF.

Any hint for that?

Thanks
Tom

**Comment by peterdemartini** [comment]
Your images should be absolute paths, or you can set the templatePath to the folder of the html and assets.

**Comment by TomFreudenberg** [comment]
Hi Peter @peterdemartini 

I set the src="" to an absolute path but also not rendered in PDF.

How to set the templatePath via command line option? I can't identify the right option.

```
node_modules/html5-to-pdf/command.js --help

  Usage: command [options] <path/to/html-file-path>

  Options:

    -h, --help                   output usage information
    -V, --version                output the version number
    -i --include <path>..<path>  path to either a javascript asset, or a css asset
    --page-size [size]           'A3', 'A4', 'Legal', 'Letter' or 'Tabloid'
    --margin-type [n]            Specify the type of margins to use: 0 - default, 1 - none, 2 - minimum
    --landscape                  If set it will change orientation to landscape from portriat
    --print-background           Whether to print CSS backgrounds
    -t --template [template]     The template to used. Defaults to html5bp.
    -d --render-delay [millis]   Delay before rendering the PDF (give HTML and CSS a chance to load)
    -o --output <path>           Path of where to save the PDF
```

**Comment by TomFreudenberg** [comment]
Hi Peter @peterdemartini 

any news here? It might be great if you could show a small (gist) example?

Thanks for feedback
Tom

**Comment by peterdemartini** [comment]
Hi @TomFreudenberg 

I added support for the `template-path` in the cli. I made an examples folder to the project that show how to do it.

**Comment by TomFreudenberg** [comment]
Hi Peter @peterdemartini 

thanks for that update - it works for me 👍 

I just found that way of "addressing" a bit confusing because you can't anymore preview changes in your browser due to file-pathes:

`/img/` points to `./examples/templates/basic/img/` 

Why aren't you able to address _relative_ pathes?

Anyway ... thanks for your help and work.

Tom


P.S.: I still struggling with #8

**Comment by peterdemartini** [comment]
Addressing relativePaths in this is not something I want to do, since I would have to modify the users HTML and CSS. In order to translate the relative paths I would find all relative paths, and convert them, which is difficult, and it will have unintended side effects.

You might be able to set the absolute image path the file:// prefix.
