### ISSUE TITLE
No margin per CSS

### ISSUE THREAD

**Issue by TomFreudenberg** [peterdemartini/html5-to-pdf#8]
Hi Peter @peterdemartini 

I am trying to set my own margins for print-out but they are _ignored_ during PDF creation. If I take a look at the HTML output the margins are ok.

```
node_modules/html5-to-pdf/command.js --page-size A4 --landscape --margin-type 1 --include demo.css --output demo.pdf demo.html
```

my CSS looks like:

```
body {
  margin-top: 4cm;
}
```

Any hint for that?

Thanks
Tom

**Comment by peterdemartini** [comment]
You'll need to use print css to get the margins to work properly. 

This documentation might be helpful, https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/. 

Let me know if that works for you.

**Comment by TomFreudenberg** [comment]
Hi Peter @peterdemartini 

maybe I am wrong, but that also "only" changes the orientation to landscape. The margins are also not set.

```
@page {
  size: A4 landscape;
  margin-top: 4cm;
  margin-left: 4cm;
}
```

I also read: https://www.w3.org/TR/css3-page/#margin-boxes

Thanks for any help
Tom

**Comment by TomFreudenberg** [comment]
Hi Peter @peterdemartini 

I have tried to extend your new examples demo and appended following to `basic.css`

```
@page {
  size: A4 landscape;
  margin-top: 4cm;
  margin-left: 4cm;
}
```

but the margins don't work.

Any idea?
Thx for your help, Tom

**Comment by peterdemartini** [comment]
@TomFreudenberg 

I created an example of how to add custom margin. See the latest commit. Let me know if that works for you.

**Comment by TomFreudenberg** [comment]
Hi Peter @peterdemartini 

thanks for your demo and support.

That works!
