### ISSUE TITLE
Command option --render-delay does not work

### ISSUE THREAD

**Issue by TomFreudenberg** [peterdemartini/html5-to-pdf#9]
Hi Peter @peterdemartini 

when adding a number of images, the Nightmare engine needs to wait a bit for rendering before ready to produce the pdf. This time the options as described:

```
-d --render-delay [millis]       Delay before rendering the PDF (give HTML and CSS a chance to load)
```

does not work. Neither `-d` nor `--render-delay`.

I get following error after updating your `basic-cli-test.sh`:

```
  $project_dir/command.js \
    --template-path $template_dir \
    --include $assets_dir/basic.css,$assets_dir/custom-margin.css \
    --margin-type 2 \
    --render-delay 5000 \
    $assets_dir/basic.html -o $output_file || exit 1
```

returns

```
Error: Failed to execute 'querySelector' on 'Document': '5000' is not a valid selector.
```

Is this option really (already) implemented?

Thanks for help again
Tom

**Comment by peterdemartini** [comment]
@TomFreudenberg I just needed to parseInt the renderDelay since it was being sent as a string.
